#ifndef PHYSICS
#define PHYSICS
#include <inttypes.h>

/*** CAN-bus spesific ***/
#define MOTOR_EPOS_LEFT_FRONT_ID 0x0C
#define MOTOR_EPOS_RIGHT_FRONT_ID 0x0D
#define MOTOR_EPOS_LEFT_REAR_ID 0x0E
#define MOTOR_EPOS_RIGHT_REAR_ID 0X0F

/*** Errors ***/
#define MOTOR_ERROR   (-1)
#define MOTOR_TIMEOUT (-2)

#define DRIVING_MOTOR_PPR     4096.0f
#define N_SECONDS_PER_MINUTE 60.0f

#define DRIVING_MOTOR_RPM_TO_COUNTS_PER_SEC  ((DRIVING_MOTOR_PPR / N_SECONDS_PER_MINUTE) * 10.0f)
#define DRIVING_MOTOR_COUNTS_PER_SEC_TO_RPM  (1.0f / DRIVING_MOTOR_RPM_TO_COUNTS_PER_SEC)

#define DRIVING_MOTOR_REGISTER_MULTIPLIER     10.0f

#define MOTOR_ACC_MULTIPLIER 4096.0f/10.0f

#endif // LIBMOTOR_H
